[
  {
    animated: null,
    name: "KEKW",
    id: "945993093126164480",
    reaction: {
      message: {
        channelId: "599691875741335553",
        guildId: "352399527925383170",
        id: "1465967229370765419",
        createdTimestamp: 1769584223836,
        type: 0,
        system: false,
        content: "<@1465233109640286261>",
        author: [],
        pinned: false,
        tts: false,
        nonce: "1465967228405940224",
        embeds: [],
        components: [],
        attachments: {},
        stickers: {},
        position: null,
        roleSubscriptionData: null,
        resolved: null,
        editedTimestamp: null,
        reactions: [ReactionManager],
        mentions: [MessageMentions],
        webhookId: null,
        groupActivityApplication: null,
        applicationId: null,
        activity: null,
        flags: [MessageFlagsBitField],
        reference: null,
        interactionMetadata: null,
        interaction: null,
        poll: null,
        messageSnapshots: {},
        call: null,
      },
      me: false,
      meBurst: false,
      users: {},
      _emoji: {},
      burstColors: null,
      count: 1,
      countDetails: { burst: 0, normal: 1 },
    },
  },
  {
    animated: null,
    name: "❤️",
    id: null,
    reaction: {
      message: {
        channelId: "599691875741335553",
        guildId: "352399527925383170",
        id: "1465967229370765419",
        createdTimestamp: 1769584223836,
        type: 0,
        system: false,
        content: "<@1465233109640286261>",
        author: [],
        pinned: false,
        tts: false,
        nonce: "1465967228405940224",
        embeds: [],
        components: [],
        attachments: {},
        stickers: {},
        position: null,
        roleSubscriptionData: null,
        resolved: null,
        editedTimestamp: null,
        reactions: [],
        mentions: [],
        webhookId: null,
        groupActivityApplication: null,
        applicationId: null,
        activity: null,
        flags: [MessageFlagsBitField],
        reference: null,
        interactionMetadata: null,
        interaction: null,
        poll: null,
        messageSnapshots: {},
        call: null,
      },
      me: false,
      meBurst: false,
      users: {},
      _emoji: [Circular * 2],
      burstColors: null,
      count: 1,
      countDetails: { burst: 0, normal: 1 },
    },
  },
];
